In [1]:
import pandas as pd
import numpy as np
import string

In [2]:
df = pd.read_csv("TypeOfMentalHealthDisorder")
print(df)

FileNotFoundError: [Errno 2] No such file or directory: 'TypeOfMentalHealthDisorder'

In [2]:
df = pd.read_csv("TypeOfMentalHealthDisorder.csv")
print(df)

         index       Entity Code  Year Schizophrenia (%) Bipolar disorder (%)  \
0            0  Afghanistan  AFG  1990           0.16056             0.697779
1            1  Afghanistan  AFG  1991          0.160312             0.697961
2            2  Afghanistan  AFG  1992          0.160135             0.698107
3            3  Afghanistan  AFG  1993          0.160037             0.698257
4            4  Afghanistan  AFG  1994          0.160022             0.698469
...        ...          ...  ...   ...               ...                  ...
108548  108548     Zimbabwe  ZWE  2013      303564.60359                  NaN
108549  108549     Zimbabwe  ZWE  2014     311665.769283                  NaN
108550  108550     Zimbabwe  ZWE  2015     320638.507158                  NaN
108551  108551     Zimbabwe  ZWE  2016     330437.353798                  NaN
108552  108552     Zimbabwe  ZWE  2017     340583.157405                  NaN

       Eating disorders (%)  Anxiety disorders (%)  Drug use disorders (%)  \
0                  0.101855               4.828830                1.677082
1                  0.099313               4.829740                1.684746
2                  0.096692               4.831108                1.694334
3                  0.094336               4.830864                1.705320
4                  0.092439               4.829423                1.716069
...                     ...                    ...                     ...
108548                  NaN                    NaN                     NaN
108549                  NaN                    NaN                     NaN
108550                  NaN                    NaN                     NaN
108551                  NaN                    NaN                     NaN
108552                  NaN                    NaN                     NaN

        Depression (%)  Alcohol use disorders (%)
0             4.071831                   0.672404
1             4.079531                   0.671768
2             4.088358                   0.670644
3             4.096190                   0.669738
4             4.099582                   0.669260
...                ...                        ...
108548             NaN                        NaN
108549             NaN                        NaN
108550             NaN                        NaN
108551             NaN                        NaN
108552             NaN                        NaN

[108553 rows x 11 columns]

C:\Users\aspire 3\AppData\Local\Temp\ipykernel_19904\2787823467.py:1: DtypeWarning: Columns (5,6) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("TypeOfMentalHealthDisorder.csv")

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 108553 entries, 0 to 108552
Data columns (total 11 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   index                      108553 non-null  int64
 1   Entity                     108553 non-null  object
 2   Code                       103141 non-null  object
 3   Year                       108553 non-null  object
 4   Schizophrenia (%)          25875 non-null   object
 5   Bipolar disorder (%)       19406 non-null   object
 6   Eating disorders (%)       100236 non-null  object
 7   Anxiety disorders (%)      6468 non-null    float64
 8   Drug use disorders (%)     6468 non-null    float64
 9   Depression (%)             6468 non-null    float64
 10  Alcohol use disorders (%)  6468 non-null    float64
dtypes: float64(4), int64(1), object(6)
memory usage: 9.1+ MB

In [4]:
df.isnull().sum()

index                             0
Entity                            0
Code                           5412
Year                              0
Schizophrenia (%)             82678
Bipolar disorder (%)          89147
Eating disorders (%)           8317
Anxiety disorders (%)        102085
Drug use disorders (%)       102085
Depression (%)               102085
Alcohol use disorders (%)    102085
dtype: int64

In [5]:
df.columns

Index(['index', 'Entity', 'Code', 'Year', 'Schizophrenia (%)',
       'Bipolar disorder (%)', 'Eating disorders (%)', 'Anxiety disorders (%)',
       'Drug use disorders (%)', 'Depression (%)',
       'Alcohol use disorders (%)'],
      dtype='object')

In [6]:
df.notna().sum()

index                        108553
Entity                       108553
Code                         103141
Year                         108553
Schizophrenia (%)             25875
Bipolar disorder (%)          19406
Eating disorders (%)         100236
Anxiety disorders (%)          6468
Drug use disorders (%)         6468
Depression (%)                 6468
Alcohol use disorders (%)      6468
dtype: int64

In [7]:
df.drop(columns=['index'],axis-1)

SyntaxError: positional argument follows keyword argument (4250484360.py, line 1)

In [7]:
df = df.dropna()
print(df)

      index       Entity Code  Year Schizophrenia (%) Bipolar disorder (%)  \
0         0  Afghanistan  AFG  1990           0.16056             0.697779
1         1  Afghanistan  AFG  1991          0.160312             0.697961
2         2  Afghanistan  AFG  1992          0.160135             0.698107
3         3  Afghanistan  AFG  1993          0.160037             0.698257
4         4  Afghanistan  AFG  1994          0.160022             0.698469
...     ...          ...  ...   ...               ...                  ...
6463   6463     Zimbabwe  ZWE  2013           0.15567             0.607993
6464   6464     Zimbabwe  ZWE  2014          0.155993              0.60861
6465   6465     Zimbabwe  ZWE  2015          0.156465             0.609363
6466   6466     Zimbabwe  ZWE  2016          0.157111             0.610234
6467   6467     Zimbabwe  ZWE  2017          0.157963             0.611242

     Eating disorders (%)  Anxiety disorders (%)  Drug use disorders (%)  \
0                0.101855               4.828830                1.677082
1                0.099313               4.829740                1.684746
2                0.096692               4.831108                1.694334
3                0.094336               4.830864                1.705320
4                0.092439               4.829423                1.716069
...                   ...                    ...                     ...
6463             0.117248               3.090168                0.766280
6464             0.118073               3.093964                0.768914
6465              0.11947               3.098687                0.771802
6466             0.121456               3.104294                0.772275
6467             0.124443               3.110926                0.772648

      Depression (%)  Alcohol use disorders (%)
0           4.071831                   0.672404
1           4.079531                   0.671768
2           4.088358                   0.670644
3           4.096190                   0.669738
4           4.099582                   0.669260
...              ...                        ...
6463        3.128192                   1.515641
6464        3.140290                   1.515470
6465        3.155710                   1.514751
6466        3.174134                   1.513269
6467        3.192789                   1.510943

[5488 rows x 11 columns]

In [8]:
df.isnull().sum()

index                        0
Entity                       0
Code                         0
Year                         0
Schizophrenia (%)            0
Bipolar disorder (%)         0
Eating disorders (%)         0
Anxiety disorders (%)        0
Drug use disorders (%)       0
Depression (%)               0
Alcohol use disorders (%)    0
dtype: int64

In [9]:
df.head()

,index,Entity,Code,Year,Schizophrenia (%),Bipolar disorder (%),Eating disorders (%),Anxiety disorders (%),Drug use disorders (%),Depression (%),Alcohol use disorders (%)
0,0,Afghanistan,AFG,1990,0.16056,0.697779,0.101855,4.828830,1.677082,4.071831,0.672404
1,1,Afghanistan,AFG,1991,0.160312,0.697961,0.099313,4.829740,1.684746,4.079531,0.671768
2,2,Afghanistan,AFG,1992,0.160135,0.698107,0.096692,4.831108,1.694334,4.088358,0.670644
3,3,Afghanistan,AFG,1993,0.160037,0.698257,0.094336,4.830864,1.705320,4.096190,0.669738
4,4,Afghanistan,AFG,1994,0.160022,0.698469,0.092439,4.829423,1.716069,4.099582,0.669260

In [10]:
df.tail()

,index,Entity,Code,Year,Schizophrenia (%),Bipolar disorder (%),Eating disorders (%),Anxiety disorders (%),Drug use disorders (%),Depression (%),Alcohol use disorders (%)
6463,6463,Zimbabwe,ZWE,2013,0.15567,0.607993,0.117248,3.090168,0.766280,3.128192,1.515641
6464,6464,Zimbabwe,ZWE,2014,0.155993,0.60861,0.118073,3.093964,0.768914,3.140290,1.515470
6465,6465,Zimbabwe,ZWE,2015,0.156465,0.609363,0.11947,3.098687,0.771802,3.155710,1.514751
6466,6466,Zimbabwe,ZWE,2016,0.157111,0.610234,0.121456,3.104294,0.772275,3.174134,1.513269
6467,6467,Zimbabwe,ZWE,2017,0.157963,0.611242,0.124443,3.110926,0.772648,3.192789,1.510943

In [12]:
df.drop(columns=['index'],axis=1)

,Entity,Code,Year,Schizophrenia (%),Bipolar disorder (%),Eating disorders (%),Anxiety disorders (%),Drug use disorders (%),Depression (%),Alcohol use disorders (%)
0,Afghanistan,AFG,1990,0.16056,0.697779,0.101855,4.828830,1.677082,4.071831,0.672404
1,Afghanistan,AFG,1991,0.160312,0.697961,0.099313,4.829740,1.684746,4.079531,0.671768
2,Afghanistan,AFG,1992,0.160135,0.698107,0.096692,4.831108,1.694334,4.088358,0.670644
3,Afghanistan,AFG,1993,0.160037,0.698257,0.094336,4.830864,1.705320,4.096190,0.669738
4,Afghanistan,AFG,1994,0.160022,0.698469,0.092439,4.829423,1.716069,4.099582,0.669260
...,...,...,...,...,...,...,...,...,...,...
6463,Zimbabwe,ZWE,2013,0.15567,0.607993,0.117248,3.090168,0.766280,3.128192,1.515641
6464,Zimbabwe,ZWE,2014,0.155993,0.60861,0.118073,3.093964,0.768914,3.140290,1.515470
6465,Zimbabwe,ZWE,2015,0.156465,0.609363,0.11947,3.098687,0.771802,3.155710,1.514751
6466,Zimbabwe,ZWE,2016,0.157111,0.610234,0.121456,3.104294,0.772275,3.174134,1.513269
6467,Zimbabwe,ZWE,2017,0.157963,0.611242,0.124443,3.110926,0.772648,3.192789,1.510943

In [13]:
df.drop(columns=['Code'],axis=1)

,index,Entity,Year,Schizophrenia (%),Bipolar disorder (%),Eating disorders (%),Anxiety disorders (%),Drug use disorders (%),Depression (%),Alcohol use disorders (%)
0,0,Afghanistan,1990,0.16056,0.697779,0.101855,4.828830,1.677082,4.071831,0.672404
1,1,Afghanistan,1991,0.160312,0.697961,0.099313,4.829740,1.684746,4.079531,0.671768
2,2,Afghanistan,1992,0.160135,0.698107,0.096692,4.831108,1.694334,4.088358,0.670644
3,3,Afghanistan,1993,0.160037,0.698257,0.094336,4.830864,1.705320,4.096190,0.669738
4,4,Afghanistan,1994,0.160022,0.698469,0.092439,4.829423,1.716069,4.099582,0.669260
...,...,...,...,...,...,...,...,...,...,...
6463,6463,Zimbabwe,2013,0.15567,0.607993,0.117248,3.090168,0.766280,3.128192,1.515641
6464,6464,Zimbabwe,2014,0.155993,0.60861,0.118073,3.093964,0.768914,3.140290,1.515470
6465,6465,Zimbabwe,2015,0.156465,0.609363,0.11947,3.098687,0.771802,3.155710,1.514751
6466,6466,Zimbabwe,2016,0.157111,0.610234,0.121456,3.104294,0.772275,3.174134,1.513269
6467,6467,Zimbabwe,2017,0.157963,0.611242,0.124443,3.110926,0.772648,3.192789,1.510943

In [14]:
df.drop(columns=['index'],axis=2)

,Entity,Code,Year,Schizophrenia (%),Bipolar disorder (%),Eating disorders (%),Anxiety disorders (%),Drug use disorders (%),Depression (%),Alcohol use disorders (%)
0,Afghanistan,AFG,1990,0.16056,0.697779,0.101855,4.828830,1.677082,4.071831,0.672404
1,Afghanistan,AFG,1991,0.160312,0.697961,0.099313,4.829740,1.684746,4.079531,0.671768
2,Afghanistan,AFG,1992,0.160135,0.698107,0.096692,4.831108,1.694334,4.088358,0.670644
3,Afghanistan,AFG,1993,0.160037,0.698257,0.094336,4.830864,1.705320,4.096190,0.669738
4,Afghanistan,AFG,1994,0.160022,0.698469,0.092439,4.829423,1.716069,4.099582,0.669260
...,...,...,...,...,...,...,...,...,...,...
6463,Zimbabwe,ZWE,2013,0.15567,0.607993,0.117248,3.090168,0.766280,3.128192,1.515641
6464,Zimbabwe,ZWE,2014,0.155993,0.60861,0.118073,3.093964,0.768914,3.140290,1.515470
6465,Zimbabwe,ZWE,2015,0.156465,0.609363,0.11947,3.098687,0.771802,3.155710,1.514751
6466,Zimbabwe,ZWE,2016,0.157111,0.610234,0.121456,3.104294,0.772275,3.174134,1.513269
6467,Zimbabwe,ZWE,2017,0.157963,0.611242,0.124443,3.110926,0.772648,3.192789,1.510943

In [15]:
df.drop(columns=['Code'],axis=1)

,index,Entity,Year,Schizophrenia (%),Bipolar disorder (%),Eating disorders (%),Anxiety disorders (%),Drug use disorders (%),Depression (%),Alcohol use disorders (%)
0,0,Afghanistan,1990,0.16056,0.697779,0.101855,4.828830,1.677082,4.071831,0.672404
1,1,Afghanistan,1991,0.160312,0.697961,0.099313,4.829740,1.684746,4.079531,0.671768
2,2,Afghanistan,1992,0.160135,0.698107,0.096692,4.831108,1.694334,4.088358,0.670644
3,3,Afghanistan,1993,0.160037,0.698257,0.094336,4.830864,1.705320,4.096190,0.669738
4,4,Afghanistan,1994,0.160022,0.698469,0.092439,4.829423,1.716069,4.099582,0.669260
...,...,...,...,...,...,...,...,...,...,...
6463,6463,Zimbabwe,2013,0.15567,0.607993,0.117248,3.090168,0.766280,3.128192,1.515641
6464,6464,Zimbabwe,2014,0.155993,0.60861,0.118073,3.093964,0.768914,3.140290,1.515470
6465,6465,Zimbabwe,2015,0.156465,0.609363,0.11947,3.098687,0.771802,3.155710,1.514751
6466,6466,Zimbabwe,2016,0.157111,0.610234,0.121456,3.104294,0.772275,3.174134,1.513269
6467,6467,Zimbabwe,2017,0.157963,0.611242,0.124443,3.110926,0.772648,3.192789,1.510943

In [16]:
df.head()

,index,Entity,Code,Year,Schizophrenia (%),Bipolar disorder (%),Eating disorders (%),Anxiety disorders (%),Drug use disorders (%),Depression (%),Alcohol use disorders (%)
0,0,Afghanistan,AFG,1990,0.16056,0.697779,0.101855,4.828830,1.677082,4.071831,0.672404
1,1,Afghanistan,AFG,1991,0.160312,0.697961,0.099313,4.829740,1.684746,4.079531,0.671768
2,2,Afghanistan,AFG,1992,0.160135,0.698107,0.096692,4.831108,1.694334,4.088358,0.670644
3,3,Afghanistan,AFG,1993,0.160037,0.698257,0.094336,4.830864,1.705320,4.096190,0.669738
4,4,Afghanistan,AFG,1994,0.160022,0.698469,0.092439,4.829423,1.716069,4.099582,0.669260

In [11]:
df.drop(["index","Code"], axis = 1, inplace = True)

In [13]:
df.columns

Index(['Entity', 'Year', 'Schizophrenia (%)', 'Bipolar disorder (%)',
       'Eating disorders (%)', 'Anxiety disorders (%)',
       'Drug use disorders (%)', 'Depression (%)',
       'Alcohol use disorders (%)'],
      dtype='object')

In [12]:
df.head()

,Entity,Year,Schizophrenia (%),Bipolar disorder (%),Eating disorders (%),Anxiety disorders (%),Drug use disorders (%),Depression (%),Alcohol use disorders (%)
0,Afghanistan,1990,0.16056,0.697779,0.101855,4.828830,1.677082,4.071831,0.672404
1,Afghanistan,1991,0.160312,0.697961,0.099313,4.829740,1.684746,4.079531,0.671768
2,Afghanistan,1992,0.160135,0.698107,0.096692,4.831108,1.694334,4.088358,0.670644
3,Afghanistan,1993,0.160037,0.698257,0.094336,4.830864,1.705320,4.096190,0.669738
4,Afghanistan,1994,0.160022,0.698469,0.092439,4.829423,1.716069,4.099582,0.669260

In [19]:
df.to_csv(r"C:\Users\aspire 3\Downloads\newTypeOfMentalHealth.xlsx")

In [20]:
df.to_csv(r"C:\Users\aspire 3\Downloads\newTypeOfMentalHealth.csv")

In [5]:
df.rename(columns={'Entity': 'Country'}, inplace=True)

In [6]:
df.to_csv(r"C:\Users\aspire 3\Downloads\newTypeOfMentalHealth2.csv")